In [1]:

import numpy as np 
import matplotlib.pyplot as plt
# display plots in this notebook
%matplotlib inline

# set display defaults
plt.rcParams['figure.figsize'] = (10, 10)        # large images 图像尺寸
plt.rcParams['image.interpolation'] = 'nearest'  # don't interpolate: show square pixels
plt.rcParams['image.cmap'] = 'gray'  # use grayscale output rather than a (potentially misleading) color heatmap

# The caffe module needs to be on the Python path;
#  we'll add it here explicitly.
import sys
caffe_root = '/home/omnisky/caffe/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')

import caffe
# If you get "No module named _caffe", either you have not built pycaffe or you have the wrong path.

In [2]:
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
# display plots in this notebook
# set display defaults
plt.rcParams['figure.figsize'] = (10, 10)        # large images 图像尺寸
plt.rcParams['image.interpolation'] = 'nearest'  # don't interpolate: show square pixels
plt.rcParams['image.cmap'] = 'gray'  # use grayscale output rather than a (potentially misleading) color heatmap
# The caffe module needs to be on the Python path;
#  we'll add it here explicitly.
import sys
caffe_root = '/home/omnisky/caffe/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')
import caffe

caffe.set_mode_gpu()
caffe.set_device(1)

In [3]:
model_def = '/home/omnisky/caffe/jobs/params/old.prototxt'
model_weights = '/home/omnisky/caffe/jobs/params/MSSC-64.caffemodel'

net_old = caffe.Net(model_def,
                model_weights,
                caffe.TEST)

In [4]:
caffe.set_device(2)
new_model_def = '/home/omnisky/caffe/jobs/params/new.prototxt'
new_model_weights = '/home/omnisky/caffe/jobs/params/MSSC-64.caffemodel'
net_new = caffe.Net(new_model_def,
                new_model_weights,
                caffe.TEST)

In [5]:
#打印所有层名
key_s = net_new.params.keys()
print net_new.params.keys()
for key0 in key_s:
    print key0

['stem1', 'stem1/bn', 'stem1/scale', 'stem2a', 'stem2a/bn', 'stem2a/scale', 'stem2b', 'stem2b/bn', 'stem2b/scale', 'stem3', 'stem3/bn', 'stem3/scale', 'stage1_1/branch1a', 'stage1_1/branch1a/bn', 'stage1_1/branch1a/scale', 'stage1_1/branch1b', 'stage1_1/branch1b/bn', 'stage1_1/branch1b/scale', 'stage1_1/branch2a', 'stage1_1/branch2a/bn', 'stage1_1/branch2a/scale', 'stage1_1/branch2b', 'stage1_1/branch2b/bn', 'stage1_1/branch2b/scale', 'stage1_1/branch2c', 'stage1_1/branch2c/bn', 'stage1_1/branch2c/scale', 'stage1_2/branch1a', 'stage1_2/branch1a/bn', 'stage1_2/branch1a/scale', 'stage1_2/branch1b', 'stage1_2/branch1b/bn', 'stage1_2/branch1b/scale', 'stage1_2/branch2a', 'stage1_2/branch2a/bn', 'stage1_2/branch2a/scale', 'stage1_2/branch2b', 'stage1_2/branch2b/bn', 'stage1_2/branch2b/scale', 'stage1_2/branch2c', 'stage1_2/branch2c/bn', 'stage1_2/branch2c/scale', 'stage1_3/branch1a', 'stage1_3/branch1a/bn', 'stage1_3/branch1a/scale', 'stage1_3/branch1b', 'stage1_3/branch1b/bn', 'stage1_3/br

In [6]:
#查看old权重
net_old_weights = net_old.params['stage4_tb/ext/pm2/b2c/scale'][0].data
print net_old_weights

[0.69580877 1.1381608  0.42339817 0.30815405 1.0879081  0.43741933
 0.22469774 0.34749576 1.0533613  0.4203483  1.9942254  1.8344021
 0.869634   0.6229136  0.51731175 1.1238428  0.94521767 1.4883888
 0.88650465 0.78627    1.0523074  1.1261088  0.9985444  0.9926344
 0.68102473 1.0958253  1.6302419  0.80550104 0.83507293 0.8347225
 1.3892229  0.78944993 1.5599685  0.9975211  0.8603405  0.727052
 1.1733983  1.2821357  0.65960926 0.583926   0.7437671  0.6682722
 0.57756513 0.687507   1.1675746  1.2316996  1.6609524  0.94039
 0.296586   1.202324   1.250863   1.0672929  0.8967713  0.9235327
 0.57498765 1.8101842  0.8280009  0.54629165 0.6898738  0.7515495
 1.9437883  1.4194021  0.6268397  0.36799315]


In [12]:
#查看new权重
net_new_weights = net_new.params['stage4_tb/ext/pm2/b2c/scale/student'][0].data
print net_new_weights   

[0.69580877 1.1381608  0.42339817 0.30815405 1.0879081  0.43741933
 0.22469774 0.34749576 1.0533613  0.4203483  1.9942254  1.8344021
 0.869634   0.6229136  0.51731175 1.1238428  0.94521767 1.4883888
 0.88650465 0.78627    1.0523074  1.1261088  0.9985444  0.9926344
 0.68102473 1.0958253  1.6302419  0.80550104 0.83507293 0.8347225
 1.3892229  0.78944993 1.5599685  0.9975211  0.8603405  0.727052
 1.1733983  1.2821357  0.65960926 0.583926   0.7437671  0.6682722
 0.57756513 0.687507   1.1675746  1.2316996  1.6609524  0.94039
 0.296586   1.202324   1.250863   1.0672929  0.8967713  0.9235327
 0.57498765 1.8101842  0.8280009  0.54629165 0.6898738  0.7515495
 1.9437883  1.4194021  0.6268397  0.36799315]


In [11]:
#读取新层列表

new_layers = []
with open('/home/omnisky/caffe/jobs/new_layers','r') as f:
    for line in f:
        new_layers.append(line)
        net_new_weights = net_new.params[line.strip('\n')][0].data
        print('this is old params ',line.strip('\n').replace('/student',''))
        net_old_weights = net_old.params[line.strip('\n').replace('/student','')][0].data
        #print net_old_weights
     #开始赋值   
        net_new.params[line.strip('\n')][0].data.flat = net_old_weights
        print('this is new params ',line.strip('\n'))
        print net_new_weights
        


('this is old params ', 'stem1')
('this is new params ', 'stem1/student')
[[[[-2.14936361e-02 -3.77855450e-01 -5.73511183e-01]
   [ 4.11147565e-01  1.61762834e-01 -4.08080876e-01]
   [ 4.24922526e-01  5.98238230e-01  1.52039379e-01]]

  [[-7.71905035e-02 -4.63553548e-01 -6.71050072e-01]
   [ 4.05625075e-01  1.34421870e-01 -4.92237359e-01]
   [ 4.26201612e-01  5.82986116e-01  9.36049521e-02]]

  [[-7.29086325e-02 -4.85367596e-01 -7.15901911e-01]
   [ 4.22556370e-01  1.27262950e-01 -4.87471610e-01]
   [ 4.93394315e-01  6.46562934e-01  1.78238273e-01]]]


 [[[-8.10580980e-03 -1.09889987e-03  2.00481303e-02]
   [ 1.83565505e-02 -1.07474178e-02 -2.14331970e-02]
   [-1.34401619e-02  5.29890042e-03 -1.08825462e-02]]

  [[ 1.08281136e-01  1.15109444e-01  1.33678362e-01]
   [ 1.13081232e-01  1.19191051e-01  8.63158852e-02]
   [ 1.20818332e-01  1.09333880e-01  1.08211897e-01]]

  [[-8.09513032e-02 -1.00642473e-01 -9.03263688e-02]
   [-8.34034905e-02 -8.81802663e-02 -1.13762543e-01]
   [-6.358422

In [13]:
#保存
res = net_new.forward()
net_new.save('/home/omnisky/caffe/jobs/params/MSCCA_new.caffemodel')
print('123')

123


In [14]:
test_model_def = '/home/omnisky/caffe/jobs/params/new.prototxt'
test_model_weights = '/home/omnisky/caffe/jobs/params/MSCCA_new.caffemodel'

net_test = caffe.Net(test_model_def,
                test_model_weights,
                caffe.TEST)
net_test_weights = net_test.params['stem1'][0].data
print net_test_weights

[[[[-2.14936361e-02 -3.77855450e-01 -5.73511183e-01]
   [ 4.11147565e-01  1.61762834e-01 -4.08080876e-01]
   [ 4.24922526e-01  5.98238230e-01  1.52039379e-01]]

  [[-7.71905035e-02 -4.63553548e-01 -6.71050072e-01]
   [ 4.05625075e-01  1.34421870e-01 -4.92237359e-01]
   [ 4.26201612e-01  5.82986116e-01  9.36049521e-02]]

  [[-7.29086325e-02 -4.85367596e-01 -7.15901911e-01]
   [ 4.22556370e-01  1.27262950e-01 -4.87471610e-01]
   [ 4.93394315e-01  6.46562934e-01  1.78238273e-01]]]


 [[[-8.10580980e-03 -1.09889987e-03  2.00481303e-02]
   [ 1.83565505e-02 -1.07474178e-02 -2.14331970e-02]
   [-1.34401619e-02  5.29890042e-03 -1.08825462e-02]]

  [[ 1.08281136e-01  1.15109444e-01  1.33678362e-01]
   [ 1.13081232e-01  1.19191051e-01  8.63158852e-02]
   [ 1.20818332e-01  1.09333880e-01  1.08211897e-01]]

  [[-8.09513032e-02 -1.00642473e-01 -9.03263688e-02]
   [-8.34034905e-02 -8.81802663e-02 -1.13762543e-01]
   [-6.35842234e-02 -6.93002790e-02 -7.09324554e-02]]]


 [[[ 1.86988920e-01  4.1525253